### ISSUE TITLE
After update to 63.0.3239.84 weird stuff going on

### ISSUE THREAD

**Issue by sirx** [gcarq/inox-patchset#127] opened 2017-12-20 08:15 UTC
I was updating to the latest binary from AUR and it's weird, just look at the screenshots.

![cf5990de](https://user-images.githubusercontent.com/14188379/34197176-8fa27aec-e565-11e7-96af-530bc3e2da9c.png)

The player sometimes doesn't load the buttons and the colors are little different than they were before the update, without custom css it looks the same.

![65bd2a54](https://user-images.githubusercontent.com/14188379/34197234-d115dbf4-e565-11e7-8da1-58df6473922e.png)

Also there is a image on a website I visit sometimes with src(unknown) it looks like this on the page
![bee6286a](https://user-images.githubusercontent.com/14188379/34197310-2da0ad68-e566-11e7-8b29-dec1d03567fa.png)

![96f0a358](https://user-images.githubusercontent.com/14188379/34197276-0156aa78-e566-11e7-89e7-0a9eb4bb5ab9.png)

My friends say after updating the normal Chromium at least the weird image was gone, any idea what happened?

**Comment by Eloston** [comment] 2017-12-22 13:28
Interesting, but your description is too high-level with too few details to be diagnosable. Were you able to narrow down the issue any further?

**Comment by sirx** [comment] 2017-12-22 22:54
I reverted back to v62, that's all I did

**Comment by sirx** [comment] 2017-12-24 02:01
I don't know how to track down the issue but I can say that the issue with the videoplayer on some direct linking sites is still broken in Chromium Version 63.0.3239.108 the console doesn't give me any errors.

I will watch the future of Chromium but I will stick with last v62 build as long as it's shitty like that, btw I love your work!

**Comment by Eloston** [comment] 2017-12-26 07:33
> I don't know how to track down the issue but I can say that the issue with the videoplayer on some direct linking sites is still broken in Chromium Version 63.0.3239.108 the console doesn't give me any errors.

That is strange. I'm out of ideas, unfortunately.

> btw I love your work!

Thanks! I'd like to credit @xsmile who's been doing all the heavy-lifting for Inox as of late.

**Comment by gcarq** [comment] 2018-01-12 15:02
@sirx Is this still an issue with 63.0.3239.132-2?

**Comment by sirx** [comment] 2018-01-18 02:20
@gcarq sorry for my late answer…

Just updated inox to Pakete (1) inox-bin-63.0.3239.132-3

and the issue is still there.

The issue happens for me only on this site https://krautshare.net/u/sbtyvt.webm and I talked to other people hosting/using Pomf clones and they mostly report the same with Chromium so it's probably not an Inox specific problem.

Same issue happens on this page https://files.catbox.moe/lgr6ha.webm

In the IRC we talked about that issue too because I thought it would be because of the webserver and looked deeper into that but it was not the webserver, it's something browser specific for sure, because in v62 it just works as expected.

Maybe you know whats going on and could do some research on it if you like ^^

Anyways great work and thanks for keeping it up 2 date!

**Comment by Eloston** [comment] 2018-01-18 03:59
@sirx Thanks for that link. I was able to reproduce the issue, and the DevTools Console printed the following lines multiple times (with the second link):

```
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAAAXNSR0IArs4c6QAABqVJREFUeNrt3ctrFVccwHH/TsX3C3xgXCgoGBBfiOBjoSi6ECKKEjduVFwoLtyotcZUS9KEJiYYmzYmbUyT+Gj7E1vcdM65ucbM47P4LO8E5s43d86ZMzPL5ufnH0FTLbMTEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAAQAAgABgABAACAAEAAIAASAAOwEBAACAAGAAEAAIAAQQIX19fX1nj17dqyjo2NmzZo175cvX/4X/y/2Ueyr2Gex7wRQUW/fvn185syZ1ytWrPjowF6Y2HexD2NfCqBiB39nZ+eUg/jriH1Z1whqGUD813Lgfl2xTwVQkXN+pz2LczpUxzFB7QKIwZsDd...dXpqZEPz+LtK37hhfzYb+til9RAdRgNWh8kakxQczSpLYTN9oXbSPGHkWfjxf3VSmAWBclgJosh46DM7Wt1CrSeNpE0efjqdRFn4+3V1YpgFjrJICaBBCzQ6kp0lhKXbSNeORKOwPhnDvFynLwV+3WTgFkiOsERduK+wnaOYBjiXTR5+M9xlUJIKZ163jxs9EBxMWyom3FTTVFn4+HbxV9Pl6i0c7nyxJAZ2fnVF3fitPoAOKKcdG24s6y1AWx1PLodj6/1AHEaU/856/zK6EaHUBqWi+uBxR9Pm6GL/p8HDjtfH4pAoh9ErM9MeBtwksBLYaj0QSAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAQAAgABAACAAGAAEAAIAAEYCcgABAACAAEAAIAAUCt/Q0TT+YRvd35vwAAAABJRU5ErkJggg==' because it violates the following Content Security Policy directive: "img-src 'self'".
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4AMOExktvVBUhQAAAfdJREFUeNrt3CGvTwEYwOHLzGaMsQmKIlAoGkXTNMJvo9E0USKZRKOJokRBIUmSoghsbHez2Wx393KkE3wAxfs82/sF3vMr93/fczY2AAAAAAAAAAAAAAAAAAAAAAAA/oHqWXXcJuYGsFQ/qlvVHhuZGcA676tztjI3gKX6VT2qDtvOzADW+VpdrXbZ0swA1nlVnbKpuQEs1VZ1t9pnYzMDWOdjddHW5gawztPqmO3NDWCpvlc3q922ODOAdd5VZ21ybgBLtVM9rA7Z6MwA1vlSXbHVuQGs86I6YbtzA1iqn9Xtaq8tzwxgnQ/VBZueG8BS/a6eVEdtfGYA62xWN/x2MDeAdd5WZ2x/bgBLtV3drw54CjMDWOdTdcmTmBvAOo5ThwfgOFUAfx2nnvd05gaw/nbwuDriKc0MYJ1v1TXHqXMDWOe149TZAThOFUBb1R0BzAzgZXXSE5sXgDeUhgbgHcXhPwR5S9lPwUwKwD+Dhgbg38FDA9iu7lX7PYV5AbypTtv+vAA2q+v+pp8XgLPwwQF4MWRoAF4NGxzAcy+Hzgzgc3XZVucFsFM9qA7a6LwAfCJmaAA+EjU4AJ+JGxqAD0UODcA17uAAHGMODcAx5tAAHGMODsAx5tAAHGMODsAxJgAAAAAAAAAAAAAAAAAAAAAA8N/5A5T9diGrOmvNAAAAAElFTkSuQmCC' because it violates the following Content Security Policy directive: "img-src 'self'".
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4AMOFDsqgcmRgwAABANJREFUeNrtnc+LVlUch9UxMxxxk6kRpvgHtNIkwUTwT5DwcREpammLxJVGqK3aJbqRcOlOFyKabYsUN5OKMoHuDJIaksAKf4xz3dyBd9O833Pnvtx77n0euMv5nh+fh3nf955zz12wQERERERERERERERERERERERERERERERERERERKRDAGPOQr8F+Au4AOwD3nJG+idAMXC9AK4CO4HXnJ3+CTB4PQS+AJY5S/mGe3weAsxeU8BBYLEzmln4QFGDALPXXeADZzaj8GsWoACmgW+A153lDMIfgQCz1y1gnbPd8vBHKEAB/Al86Ky3OPygALuAy8CzChI8B3D2Wxp+RICBGquBr8tv/SkSvAT2m...W47ZfAfgtwzp+B/RZgrzeCvBXsrWAXg4bWuu5iUPcE2B0ct8vBHRRgMrpV3A0h3RTALWE9FuC7hDFHNoUeVIC8toUvTRjzUbeF1yfQiYYFmARWJvR3mQ+GtFiCRAF+Tn1ngI+GtVyCoAAzwOnUAx18ODQDCQJt/FL1yNfg4+HHTLJBCQL1xyr264AHRGQgwYj6synwr78AjphewxKMoB/RQ6LueUhUCySouf3VwH2PictIghrbfTfhoMjTJtUSCWpqbyPwu0fFZihBDe14WHTOEsyjtsfFd0GCCvXGy5q+MKILEiR+wz/hK2M6JkHg73YBlxI+531pVE4SBP6m6m3mKWCbs95yCUYkwG1fHJmJBDUL4Ktjc5OgRgHueXs3QwlqEMDXx3dckv8L/iFw2PX8fgkwDVwFPnIptz8CPAYuljt8Vjkj/RNgzFkQERERERERERERERERERERERERERERERERERGRtvAK4ID6HNl6lhUAAAAASUVORK5CYII=' because it violates the following Content Security Policy directive: "img-src 'self'".
```

Since this is a browser-rendered page, and the CSP for internal resources are determined by the HTML code inside the browser, this is a browser bug. Also, since these resources aren't modified by Inox, this is a Chromium bug.

This should be a straight-forward bug to fix, so there may be a patch somewhere in the Chromium bug tracker already.

**Comment by sirx** [comment] 2018-01-19 00:56
I never reported a issue in chromium I just hope it gets fixed soon by them, thanks for the help!
We'll see what the future brings it's not like this is a game breaker, it's just not nice to look at :D 

Thanks for your help guys!

**Comment by alucard0134** [comment] 2018-01-19 00:58
I might add that this issue appears to be resolved by the devs in canary. I've had users report issues similarly to this, manually adding the hashs to my CSP table doesnt resolve it oddly enough

**Comment by sirx** [comment] 2018-01-19 01:00
Yeah @alucard0134 I also played with the CSP settings but that didn't change much, one time however I had the player stuff visible, but I couldn't reproduce that ever again.

**Comment by sirx** [comment] 2018-01-19 02:01
Thanks to @alucard0134 who found a solution for the problem, just stole his code and used it in my CSP settings and it works now!
```default-src 'self' https://krautshare.net; img-src 'self' https://krautshare.net data:; style-src 'unsafe-inline'; font-src 'self'; frame-src 'self'; object-src 'none'; script-src 'sha256-T1Rs30scqXyyciODp/c4qiveH0kpYMxeNML3SE1a1pw='```

https://krautshare.net/u/rmluzs.webm
![8f6f7b24](https://user-images.githubusercontent.com/14188379/35131198-feefd6f8-fcc4-11e7-896e-e05e82c001b7.png)

**Closed** 2018-06-21 18:30 UTC
