### ISSUE TITLE
Possible: I'm compiling online

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#67] opened 2017-03-18 23:53 UTC
i'm  compiling inox
online
https://build.opensuse.org/package/show/home:meh924f:archlinux/inox

**Comment by triceratops1** [comment] 2017-03-19 00:41
AFIK   it would work
https://build.opensuse.org/package/live_build_log/home:meh924f:archlinux/inox/standard/i586
https://build.opensuse.org/package/live_build_log/home:meh924f:archlinux/inox/standard/x86_64

**Comment by gcarq** [comment] 2017-03-20 20:15
Thanks, this helps a lot!, but please use the designated issue for this. Duplicate of #42

**Closed by gcarq** 2017-03-20 20:15 UTC

**Comment by triceratops1** [comment] 2017-03-20 21:56
it my attempt i found a new issue 


doesnt read icu

now works, adding this line to package function  
cp -a out/Release/icudtl.dat "$pkgdir/usr/lib/$pkgname/"

https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/chromium/chromium-57.0.2987.98.ebuild

**Comment by triceratops1** [comment] 2017-03-20 21:58
thanks

**Comment by triceratops1** [comment] 2017-03-20 22:06
thanks @Eloston
