### ISSUE TITLE
Enhacement: add tor+i2p direct access

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#45] opened 2016-12-11 02:02 UTC
You could add i2p and tor direct accesses with adding some lines to the pkgbuild
such as these
https://gist.github.com/triceratops1/d1dc789d44a607e2d0902d2f0040b94a  

what does these lines?

Create 2 desktop files (inox-i2p, inox-tor)
Makes these desktop files open inox with tor or i2p (with counter dns-leak countermeasures)

**Comment by gcarq** [comment] 2016-12-12 09:28
I like your engagement, but it is **NOT** recommended to run inox with tor or i2p, because there is a high possibility of unseen tracking features in the code and with each update.

You can create a PR for README.md which describes how to use a proxy, but i cannot and will not implement these changes.

**Comment by triceratops1** [comment] 2016-12-14 00:18
OK
for inox  torified:
inox  --proxy-server="socks5://localhost:9050" --host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE localhost"

explanation: https://www.chromium.org/developers/design-documents/network-stack/socks-proxy  

The flag host-resolver-rules, forces inox to use the tor's DNS
The flag EXCLUDE, lets inox resolve the proxy 
http://tor.stackexchange.com/questions/3435/how-do-i-configure-chrome-to-use-tor

For I2P
https://www.internalpointers.com/post/run-chrome-chromium-proxy-settings-linux

inox --proxy-server="http://127.0.0.1:4444"
doen't need host-resolver*rules and EXCLUDE, because i2p its a closed networs (the dns is throught i2p, no clearnet)

**Comment by gcarq** [comment] 2016-12-14 19:19
Thanks. Added to README

**Comment by triceratops1** [comment] 2016-12-15 23:08
@gcarq   Could you add the warning:

If you have a proxy extension, this config couldn't work?

**Comment by triceratops1** [comment] 2016-12-16 22:58
pd could you merge #46 with this issue?

its a readme enhacement too  (a sandbox, nice if you trorify/i2pify)+memory saving (double sandbox, the inox's hardened+firejail )

**Comment by gcarq** [comment] 2016-12-17 00:33
Closed. Duplicate of https://github.com/gcarq/inox-patchset/issues/46

**Closed by gcarq** 2016-12-17 00:33 UTC
Labels: wontfix
